[package]
name = "fuzz-afl"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "btree_ops_afl"
path = "src/btree_ops.rs"
test = false
doc = false
bench = false

[dependencies]
afl = "*"
arbitrary = "*"

btree-test-utils = { path = "../zkb-tree/btree-test-utils" }
