[package]
name = "btree-test-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
zkb-tree = { path = "../" }
proptest-derive = { version = "0.5" }
proptest = { version = "1" }
sha2 = "0.10"
arbitrary = { version = "1", features = ["derive"] }
itertools = "0.14.0"
